spring.application.name=Expense
spring.datasource.url=jdbc:mysql://host.docker.internal:3307/expense
spring.datasource.username=root
spring.datasource.password=Harish@230
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForExpenseWiseApplication123456789
jwt.expiration=86400000
server.port=8081